export { PaintComponent } from './Paint';
export { PaintsComponent } from './Paints';
export { HeaderComponent } from './Header';
export { SelectComponent } from './Select';
export { FiltersComponent } from './Filters';
export { InputComponent } from './Input';
export { ThemeButtonComponent } from './ThemeButton';
export { PaginationComponent } from './Pagination';
export { InputRangeComponent } from './InputRange';
